parameters:
  simplethings.zetawebmail.mail.class: "SimpleThings\ZetaWebmailBundle\Mailbox\Mail"
  simplethings.zetawebmail.listlayout: "SimpleThingsZetaWebmailBundle::standalone.html.twig"

services:
  simplethings.zetawebmail.mailparser:
    class:      ezcMailParser
    arguments:  [ "@simplethings.zetawebmail.mailparser.options" ]

  simplethings.zetawebmail.mailparser.options:
    class:      ezcMailParserOptions
    arguments:
      0:
        mailClass: %simplethings.zetawebmail.mail.class%

  simplethings.zetawebmail.security.admin_party:
    class: SimpleThings\ZetaWebmailBundle\Security\AdminPartySecurity

  simplethings.zetawebmail.security.zeta_mail_role:
    class: SimpleThings\ZetaWebmailBundle\Security\ZetaMailRoleSecurity
    arguments: [ "@security.context" ]
    
  simplethings.zetawebmail.data_collector:
    class: SimpleThings\ZetaWebmailBundle\DataCollector\MessageDataCollector
    arguments: [ "@?simplethings.zetawebmail.transport" ]
    tags:
        - { name: data_collector, template: "SimpleThingsZetaWebmailBundle:Collector:zetawebmail", id: "zetawebmail" }

  simplethings.zetawebmail.fosuser.mailer:
    class: SimpleThings\ZetaWebmailBundle\UserBundle\ZetaMailer
    arguments:
      0: "@simplethings.zetawebmail.transport"
      1: "@router"
      2: "@templating"
      3:
        confirmation.template: %fos_user.email.confirmation.template%
        resetting_password.template: %fos_user.email.resetting_password.template%
        from_email:
          confirmation: %fos_user.email.from_email%
          resetting_password: %fos_user.email.from_email%